module.exports = {
  "fspsc": "Spam score for the page's subdomain.",
  "ftrp" : "The normalized (ten-point, logarithmically-scaled) MozTrust of the subdomain of the target URL",
  "ftrr" : "The raw (zero to one, linearly-scaled) MozTrust of the subdomain of the target URL",
  "fuid" : "The number of internal and external, equity and non-equity links to the subdomain of the target URL",
  "lrid" : "Internal ID of the link",
  "lsrc" : "Internal ID of the source URL",
  "ltgt" : "Internal ID of the target URL",
  "lufeid" : "The number of external (from other subdomains), equity links to pages on the target URLs subdomain",
  "lufejp" : "The normalized (logarithmically-scaled) sum of MozRank from external links on all pages of the subdomain of the target URL",
  "lufejr" : "The raw (linearly-scaled) sum of MozRank from external links on all pages of the subdomain of the target URL",
  "lufid"  : "The number of domains with at least one link to any page on the subdomain of the target URL",
  "lufipl" : "The number of domains with at least one link to any page on the subdomain of the target URL",
  "lufjp"  : "The normalized (logarithmically-scaled) sum of the MozRank of all the pages of the subdomain of the target URL",
  "lufjr"  : "The raw (linearly-scaled) sum of the MozRank of all the pages of the subdomain of the target URL",
  "lufmrp" : "The normalized (ten-point, logarithmically-scaled) measure of the MozRank of the subdomain of the target URL",
  "lufmrr" : "The raw (zero to one, linearly-scaled) measure of the MozRank of the subdomain of the target URL",
  "luftrp" : "The normalized (ten-point, logarithmically-scaled) measure of the MozTrust of the subdomain of the target URL",
  "luftrr" : "The raw (zero to one, linearly-scaled) measure of the MozTrust of the subdomain of the target URL",
  "lufuid" : "The number of internal and external equity and non-equity links to the subdomain of the target URL",
  "lupda"  : "The normalized (zero to one hundred, logarithmically-scaled) domain authority of the target URL's paid-level domain",
  "lupdar" : "The raw (zero to one, linearly-scaled) domain authority of the target URL's paid-level domain",
  "lupeid" : "The number of external equity links from other root domains to pages on the target URL's root domain",
  "lupejp" : "The normalized (logarithmically-scaled) sum of MozRank gained from external links on all pages of the paid-level domain of the target URL",
  "lupejr" : "The raw (linearly-scaled) sum of MozRank gained from external links on all pages of the paid-level domain of the target URL",
  "lupid"  : "The number of domains with at least one link to any page on the paid-level domain of the target URL",
  "lupjp"  : "The normalized (logarithmically-scaled) sum of MozRank gained from all pages on the paid-level domain of the target URL" ,
  "lupjr"  : "The raw (linearly-scaled) sum of MozRank gained from all pages on the paid-level domain of the target URL",
  "lupmrp" : "The normalized (ten-point, logarithmically-scaled) measure of the MozRank of the paid-level domain of the target URL",
  "lupmrr" : "The raw (zero to one, linearly-scaled) measure of the MozRank of the paid-level domain of the target URL",
  "luptrp" : "The normalized (ten-point, logarithmically-scaled) measure of the MozTrust of the paid-level domain of the target URL",
  "luptrr" : "The raw (zero to one, linearly-scaled) measure of the MozTrust of the paid-level domain of the target URL",
  "lupuid" : "The number of internal and external, equity and non-equity links to the root domain of the target URL",
  "luueid" : "The number of external (from other subdomains) equity links to the target URL",
  "luuemrp" : "The normalized (ten-point, logarithmically-scaled) MozRank gained from external links of the target URL",
  "luuemrr" : "The raw (zero to one, linearly-scaled) MozRank of the target URL gained from external links",
  "luufq"  : "The fully-qualified domain name ('subdomain')",
  "luuid"  : "The number of internal and external equity and non-equity links to the target URL",
  "luuifq" : "The number of subdomains with at least one link to the target URL",
  "luuipl" : "The number of paid-level domains with at least one link to the target URL",
  "luujid" : "The number of equity links (internal or external) to the target URL",
  "luumrp" : "The normalized (ten-point, logarithmically-scaled) MozRank of the target URL",
  "luumrr" : "The raw (zero to one, linearly-scaled) MozRank of the target URL",
  "luupa"  : "The normalized (zero to one hundred, logarithmically-scaled) page authority of the target URL",
  "luupar" : "The raw (zero to one, linearly-scaled) page authority of the target URL",
  "luupl"  : "The paid-level domain name",
  "luurrid" : "Internal ID of the canonical URL",
  "luus" : "HTTP status of the target URL",
  "luut" : "The title of the target URL, if available",
  "luutrp" : "The normalized (ten-point, logarithmically-scaled) MozTrust of the target URL",
  "luutrr" : "The raw (zero to one, linearly-scaled) MozTrust of the target URL",
  "luuu" : "The canonical form of the target URL",
  "pda" : "The normalized (zero to one hundred, logarithmically-scaled) domain authority of the source URL's paid-level domain",
  "pdar" : "The raw (zero to one, linearly-scaled) domain authority of the source URL's paid-level domain",
  "peid" : "the number of external equity links to pages on the source URL's root domain",
  "pejp" : "The normalized (logarithmically-scaled) sum of the MozRank gained from external links on all pages in the paid-level domain of the source URL",
  "pejr" : "The raw (linearly-scaled) sum of the MozRank gained from external links on all pages in the paid-level domain of the source URL",
  "pid" : "The number of domains with at least one link to any page on the paid-level domain of the source URL",
  "pjp" : "The normalized (logarithmically-scaled) sum of the MozRank of all pages in the paid-level domain of the source URL",
  "pjr" : "The raw (linearly-scaled) sum of the MozRank of all the pages in the paid-level domain of the source URL",
  "pmrp" : "The normalized (ten-point, logarithmically-scaled) MozRank of the paid-level domain of the source URL",
  "pmrr" : "The raw (zero to one, linearly-scaled) measure of the MozRank of the paid-level domain of the source URL",
  "ptrp" : "The normalized (ten-point, logarithmically-scaled) MozTrust of the paid-level domain of the source URL",
  "ptrr" : "The raw (zero to one, linearly-scaled) MozTrust of the paid-level domain of the source URL",
  "puid" : "The number of internal and external equity and non-equity links to the root domain of the source URL",
  "ued" : "The number of external links to the target URL, including nofollowed links",
  "ueid" : "The number of external, equity links to the target URL",
  "uemrp" : "The normalized (ten-point, logarithmically-scaled) MozRank of the target URL gained from external links",
  "uemrr" : "The raw (zero to one, linearly-scaled) MozRank of the target URL gained from external links",
  "ufq" : "The fully qualified domain (subdomain) name",
  "uid" : "The number of internal and external equity and non-equity links to the target URL",
  "uifq" : "The number of subdomains with at least one link to the target URL",
  "uipl" : "The number of paid-level domains with at least one link to the target URL",
  "ujid" : "The number of equity links, internal or external, to the target URL",
  "umrp" : "The normalized (ten-point, logarithmically-scaled) MozRank of the target URL",
  "umrr" : "The raw (zero to one, linearly-scaled) MozRank of the target URL",
  "upa" : "The normalized (zero to one hundred, logarithmically-scaled) page authority of the target URL",
  "upar" : "The raw (zero to one, linearly-scaled) page authority of the target URL",
  "upl" : "The paid-level domain name",
  "ur" : "The canonical target URL, if there are any canonicalization tags on the URL (for example, a 301 redirect).",
  "urid" : "Internal ID of the URL",
  "urrid" : "Internal ID of the canonical URL",
  "us" : "The HTTP status of the target URL",
  "usch" : "The protocols Moz Links encountered for the target URL, and whether a canonical tag indicates a specific protocol",
  "ut" : "The title of the target URL, if a title is available",
  "utrp" : "The normalized (ten-point, logarithmically-scaled) MozTrust of the target URL",
  "utrr" : "The raw (zero to one, linearly-scaled) MozTrust of the target URL",
  "uu" : "The canonical form of the source URL (OR, for url-metrics calls, the canonical form of the target URL)",
  "ulc": "The time and date on which we last crawled the URL, returned in Unix epoch format"
}